 var errMsg={90001:"No data found.",
 90002:"Enter valid Email Id.",
 90003:"Enter a valid Contact Number.",
 90004:"Mandatory Field - Please Enter value.",
 90005:"Enter a valid Post Code.",
 90006:"This email is already registered with us. To access our services, please login.",
 90007:"Not a secure Password - Your Password should be minimum 8 characters and must contain a lower case letter, upper case letter, a digit and a special character.",
 90008:"Your secret answer is not correct. Please retry.",
 90009:"Invalid Mobile Number or Password. If forgot Password, reset your Password, else contact administrator.",
 90010:"Your account is not active or is expired. Please contact system administrator.",
 90011:"Password entered not matching. Please retry.",
 90012:"Password Reset Succesfull. Please relogin with New Password.",
 90013:"Password Reset Failed. Check your internet connection and try again.",
 90014:"Invalid user informtion. Please enter correct information in all fields.",
 90015:"Thank you for joining. Please check your email for login details.",
 90016:"New Registration failed. Sorry for inconvenience. Try again later.",
 90017:"Invalid Date for the Month.",
 90018:"Password has to contain at least 1 number.",
 90019:"Password has to contain at least 1 uppercase.",
 90020:"Password has to contain at least 1 lowercase.",
 90021:"Password has to contain at least 1 special character.",
 90022:"Password has to contain minimum 8 characters.",
 90025:"To Date should be later to From Date.",
 90026:"Database Error. Try again later.",
 90027:"Saved Successfully.",
 90028:"Confirmed Successfully.",
 90029:"Cancelled Successfully.",
 90030:"Email sent Successfully.",
 };
 